/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.objectware.editors.export;

import br.com.objectware.commons.i18n.I18N;
import br.com.objectware.commons.utils.Default;
import br.com.objectware.commons.utils.FileUtil;
import br.com.objectware.domain.enums.DataFormat;
import br.com.objectware.domain.enums.ExportFormat;
import br.com.objectware.domain.enums.FileType;
import br.com.objectware.editors.enums.SpriteDataToExport;
import br.com.objectware.editors.enums.ExportDialogAction;
import br.com.objectware.editors.enums.SpriteScale;
import br.com.objectware.editors.sprite.SpritesDataObject;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.IOException;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import org.openide.windows.WindowManager;

/**
 * Sprite list export dialog. Defines all export options.
 * 
 * @author Luciano M. Christofoletti <luciano@objectware.net>
 * @since 10/sep/2015
 */
public class SpriteExporterDialog extends javax.swing.JDialog implements ActionListener {
    
    /** The export file chooser */
    private JFileChooser exportFileChooser;
    
    /** The sprite data object */
    private SpritesDataObject dataObject;
    
    /**
     * Creates new form SpriteExporterDialog
     */
    public SpriteExporterDialog(java.awt.Frame parent, boolean modal) {
        
        super(parent, modal);
        
        this.initComponents();
        this.setupListeners();
        
        // initialize text fields
        this.elementsPerLineTextField.setText(Integer.toString(Default.HEX_TABLE_WIDTH));
        this.linePrefixTextField.setText(Default.ASM_DATA_BYTES);
    }
    
    private void setupListeners() {
        
        // setup combo box listeners
        this.exportAsComboBox.addActionListener(this);
        
        // setup buttons listeners
        this.selectOutputFileButton.addActionListener(this);
        this.exportButton.addActionListener(this);
        this.cancelButton.addActionListener(this);
    }
    
    /**
     * Set the sprite data object.
     * @param dataObject 
     */
    public void setDataObject(SpritesDataObject dataObject) {
        this.dataObject = dataObject;
    }
    
    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The
     * content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        exportAsLabel = new javax.swing.JLabel();
        exportAsComboBox = new javax.swing.JComboBox();
        outputFileLabel = new javax.swing.JLabel();
        outputFileTextField = new javax.swing.JTextField();
        selectOutputFileButton = new javax.swing.JButton();
        linePrefixLabel = new javax.swing.JLabel();
        linePrefixTextField = new javax.swing.JTextField();
        dataFormatLabel = new javax.swing.JLabel();
        dataFormatComboBox = new javax.swing.JComboBox();
        elementsPerLineLabel = new javax.swing.JLabel();
        elementsPerLineTextField = new javax.swing.JTextField();
        exportLabelsColorsCheckBox = new javax.swing.JCheckBox();
        exportLabel = new javax.swing.JLabel();
        exportComboBox = new javax.swing.JComboBox();
        buttonsPanel = new javax.swing.JPanel();
        exportButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle(I18N.getString("export.sprites"));
        setMinimumSize(new java.awt.Dimension(512, 256));
        setPreferredSize(new java.awt.Dimension(612, 264));

        mainPanel.setPreferredSize(new java.awt.Dimension(396, 168));

        org.openide.awt.Mnemonics.setLocalizedText(exportAsLabel, I18N.getString("export.as"));

        exportAsComboBox.setModel(new javax.swing.DefaultComboBoxModel(ExportFormat.values()));
        exportAsComboBox.setActionCommand(ExportDialogAction.EXPORT_AS.name());

        org.openide.awt.Mnemonics.setLocalizedText(outputFileLabel, I18N.getString("output.file"));

        org.openide.awt.Mnemonics.setLocalizedText(selectOutputFileButton, I18N.getString("select")
        );
        selectOutputFileButton.setActionCommand(ExportDialogAction.SELECT_FILE.name());

        org.openide.awt.Mnemonics.setLocalizedText(linePrefixLabel, I18N.getString("line.prefix"));

        org.openide.awt.Mnemonics.setLocalizedText(dataFormatLabel, I18N.getString("data.format"));

        dataFormatComboBox.setModel(new javax.swing.DefaultComboBoxModel(DataFormat.values()));

        org.openide.awt.Mnemonics.setLocalizedText(elementsPerLineLabel, I18N.getString("bytes.per.line"));

        exportLabelsColorsCheckBox.setSelected(true);
        org.openide.awt.Mnemonics.setLocalizedText(exportLabelsColorsCheckBox, I18N.getString("export.labels"));

        org.openide.awt.Mnemonics.setLocalizedText(exportLabel, I18N.getString("data.to.export"));

        exportComboBox.setModel(new javax.swing.DefaultComboBoxModel(br.com.objectware.editors.enums.SpriteDataToExport.values()));

        javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(outputFileLabel)
                    .addComponent(linePrefixLabel)
                    .addComponent(elementsPerLineLabel)
                    .addComponent(exportLabel)
                    .addComponent(exportAsLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addComponent(outputFileTextField)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(selectOutputFileButton))
                    .addComponent(exportAsComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addComponent(linePrefixTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(dataFormatLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(dataFormatComboBox, 0, 265, Short.MAX_VALUE))
                    .addComponent(exportComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addComponent(elementsPerLineTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(exportLabelsColorsCheckBox, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        mainPanelLayout.setVerticalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(exportAsLabel)
                    .addComponent(exportAsComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(outputFileLabel)
                    .addComponent(outputFileTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(selectOutputFileButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(linePrefixTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(linePrefixLabel)
                    .addComponent(dataFormatLabel)
                    .addComponent(dataFormatComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(elementsPerLineTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(elementsPerLineLabel)
                    .addComponent(exportLabelsColorsCheckBox))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(exportComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(exportLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        getContentPane().add(mainPanel, java.awt.BorderLayout.CENTER);

        buttonsPanel.setPreferredSize(new java.awt.Dimension(400, 38));
        buttonsPanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT, 8, 4));

        org.openide.awt.Mnemonics.setLocalizedText(exportButton, I18N.getString("export"));
        exportButton.setActionCommand(ExportDialogAction.EXPORT.name());
        buttonsPanel.add(exportButton);

        org.openide.awt.Mnemonics.setLocalizedText(cancelButton, I18N.getString("cancel")
        );
        cancelButton.setActionCommand(ExportDialogAction.CANCEL.name());
        buttonsPanel.add(cancelButton);

        getContentPane().add(buttonsPanel, java.awt.BorderLayout.PAGE_END);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel buttonsPanel;
    private javax.swing.JButton cancelButton;
    private javax.swing.JComboBox dataFormatComboBox;
    private javax.swing.JLabel dataFormatLabel;
    private javax.swing.JLabel elementsPerLineLabel;
    private javax.swing.JTextField elementsPerLineTextField;
    private javax.swing.JComboBox exportAsComboBox;
    private javax.swing.JLabel exportAsLabel;
    private javax.swing.JButton exportButton;
    private javax.swing.JComboBox exportComboBox;
    private javax.swing.JLabel exportLabel;
    private javax.swing.JCheckBox exportLabelsColorsCheckBox;
    private javax.swing.JLabel linePrefixLabel;
    private javax.swing.JTextField linePrefixTextField;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JLabel outputFileLabel;
    private javax.swing.JTextField outputFileTextField;
    private javax.swing.JButton selectOutputFileButton;
    // End of variables declaration//GEN-END:variables

    @Override
    public void actionPerformed(ActionEvent event) {
        
        // get the dialog action "type"
        ExportDialogAction action = ExportDialogAction.valueOf(event.getActionCommand());
        
        switch(action) {
            
            case SELECT_FILE:
                this.selectOutputFile();
                break;
                
            case EXPORT:
                this.exportSpriteData();
                break;
                
            case EXPORT_AS:
                this.updateDialogView();
                break;
                
            case CANCEL:
                this.setVisible(false);
                break;
        }
    }
    
    /**
     * Export sprite data file using the selected format.
     */
    private void exportSpriteData() {
        
        java.awt.Frame mainWindow = WindowManager.getDefault().getMainWindow();
        
        String outputFileName = this.outputFileTextField.getText();
        if(outputFileName == null || outputFileName.isEmpty()) {
            JOptionPane.showMessageDialog(mainWindow,
                I18N.getString("please.select.output.file"), // message
                I18N.getString("export"), // title
                JOptionPane.INFORMATION_MESSAGE);
            return;
        }   
        
        // validate the number of elements per line field
        try {
            if(Integer.parseInt(this.elementsPerLineTextField.getText()) < 1) {
                throw new NumberFormatException();
            }
        } catch(NumberFormatException nfe) {
            String field = this.elementsPerLineLabel.getText().replace(':', ' ').trim().toLowerCase();
            JOptionPane.showMessageDialog(mainWindow,
                I18N.getString("invalid.integer.number.format", field), // message
                I18N.getString("invalid.parameter.value"), // title
                JOptionPane.ERROR_MESSAGE);
            return;
        }   
        
        // create a new empty target file using the selected output file name
        java.io.File targetFile = new java.io.File(outputFileName);
        SpriteDataToExport export = (SpriteDataToExport) this.exportComboBox.getSelectedItem();
        ExportFormat format = (ExportFormat) this.exportAsComboBox.getSelectedItem();
        
        // set the data to export (default is to export all)
        boolean exportAll = export.equals(SpriteDataToExport.ALL);
        boolean exportPatterns = exportAll || export.equals(SpriteDataToExport.PATTERNS);
        boolean exportAttributes = exportAll || export.equals(SpriteDataToExport.ATTRIBUTES);
        
        try {
            // verify if the selected file name already exists or it can be created
            if(!FileUtil.createNewFile(this, targetFile)) {
                return;
            }
            
            switch(format) {
                
                case ASSEMBLY:
                    this.exportPatternsAsAssemblyCode(targetFile, exportPatterns, exportAttributes);
                    break;
                    
                case BINARY:
                    this.exportPatternsAsBinaryData(targetFile, exportPatterns, exportAttributes);
                    break;
                    
                case IMAGE:
                    this.exportPatternsAsPngImage(targetFile);
                    break;
            }
            
            // close the export dialog window and show the export success message
            this.setVisible(false);
            JOptionPane.showMessageDialog(mainWindow,
                I18N.getString("sprite.data.export.sucessful", targetFile.getName()), // message
                I18N.getString("export"), // title
                JOptionPane.INFORMATION_MESSAGE);
            
        } catch (IOException ioException) {
            JOptionPane.showMessageDialog(mainWindow,
                I18N.getString("error.writing.file", targetFile.getPath()), // dialog message
                I18N.getString("input.output.error"), // dialog title
                JOptionPane.ERROR_MESSAGE);
        }   
    }
    
    /**
     * Export the sprite patterns/attributes to an assembly file (.asm)
     * @param targetFile
     * @param exportPatterns
     * @param exportAttributes
     * @throws IOException
     * @throws NumberFormatException 
     */
    private void exportPatternsAsAssemblyCode(java.io.File targetFile, boolean exportPatterns, boolean exportAttributes)
            throws IOException, NumberFormatException {
        
        SpriteAssemblyExporter assemblyExporter = new SpriteAssemblyExporter(targetFile);
        
        assemblyExporter.setLinePrefix(this.linePrefixTextField.getText());
        assemblyExporter.setBytesPerLine(Integer.parseInt(this.elementsPerLineTextField.getText()));
        assemblyExporter.setDataFormat(((DataFormat) this.dataFormatComboBox.getSelectedItem()).getFormatter());
        assemblyExporter.setExportPatterns(exportPatterns);
        assemblyExporter.setExportAttributes(exportAttributes);
        assemblyExporter.setExportLabels(this.exportLabelsColorsCheckBox.isSelected());
        
        assemblyExporter.export(this.dataObject);
    }
    
    /**
     * Export the sprite patterns/attributes to a binary file (.bin)
     * @param targetFile
     * @param exportPatterns
     * @param exportAttributes
     * @throws IOException 
     */
    private void exportPatternsAsBinaryData(java.io.File targetFile, boolean exportPatterns, boolean exportAttributes)
            throws IOException {
        
        SpriteDataExporter binaryExporter = new SpriteDataExporter(targetFile);
        binaryExporter.setExportPatterns(exportPatterns);
        binaryExporter.setExportAttributes(exportAttributes);
        
        binaryExporter.export(this.dataObject);
    }
    
    /**
     * Export the sprite pattens to an image file (.png)
     * @param targetFile
     * @throws NumberFormatException
     * @throws IOException 
     */
    private void exportPatternsAsPngImage(java.io.File targetFile) throws IOException, NumberFormatException {
        
        SpriteImageExporter pngExporter = new SpriteImageExporter(targetFile);
        
        pngExporter.setExportColors(this.exportLabelsColorsCheckBox.isSelected());
        pngExporter.setScale((int) Math.pow(2.0, this.dataFormatComboBox.getSelectedIndex()));
        pngExporter.setSpritesPerLine(Integer.parseInt(this.elementsPerLineTextField.getText()));
        
        pngExporter.export(this.dataObject);
    }
    
    /**
     * Update the dialog visual status accordingly to the selected export format.
     */
    private void updateDialogView() {
        
        // exportFormat the format of export (asm code, binary file or image)
        ExportFormat exportFormat = (ExportFormat) this.exportAsComboBox.getSelectedItem();
        
        switch(exportFormat) {
            
            case ASSEMBLY:
                this.updateVisualElements(true);
                this.dataFormatLabel.setText(I18N.getString("data.format"));
                this.dataFormatComboBox.setModel(new javax.swing.DefaultComboBoxModel(DataFormat.values()));
                this.elementsPerLineLabel.setText(I18N.getString("bytes.per.line"));
                this.exportLabelsColorsCheckBox.setText(I18N.getString("export.labels"));
                break;
                
            case BINARY:
                this.updateVisualElements(false);
                this.exportLabel.setEnabled(true);
                this.exportComboBox.setEnabled(true);
                break;
                
            case IMAGE:
                this.updateVisualElements(false);
                this.elementsPerLineLabel.setEnabled(true);
                this.elementsPerLineLabel.setText(I18N.getString("sprites.per.line"));
                this.elementsPerLineTextField.setEnabled(true);
                this.dataFormatLabel.setText(I18N.getString("sprite.size"));
                this.dataFormatLabel.setEnabled(true);
                this.dataFormatComboBox.setModel(new javax.swing.DefaultComboBoxModel(SpriteScale.values()));
                this.dataFormatComboBox.setEnabled(true);
                this.exportLabelsColorsCheckBox.setText(I18N.getString("export.colorful.sprites"));
                this.exportLabelsColorsCheckBox.setEnabled(true);
                break;
                
            default:
                throw new RuntimeException("Option not available: " + exportFormat);
        }
    }
    
    /**
     * Enable/Disable the dialog visual components accordingly to the selected
     * export format.
     * @param status true = enable, false = disable
     */
    private void updateVisualElements(boolean status) {
        this.elementsPerLineLabel.setEnabled(status);
        this.elementsPerLineTextField.setEnabled(status);
        this.linePrefixLabel.setEnabled(status);
        this.linePrefixTextField.setEnabled(status);
        this.exportLabel.setEnabled(status);
        this.exportComboBox.setEnabled(status);
        this.dataFormatLabel.setEnabled(status);
        this.dataFormatComboBox.setEnabled(status);
        this.exportLabelsColorsCheckBox.setEnabled(status);
    }   
    
    /**
     * Select the output file name.
     */
    private void selectOutputFile() {
        
        // set up the file chooser (if not created yet)
        if(this.exportFileChooser == null) {
            this.exportFileChooser = new JFileChooser();
            this.exportFileChooser.setFileSelectionMode(JFileChooser.FILES_ONLY);
        }   
        
        // setup the file filter
        ExportFormat exportFormat = (ExportFormat) this.exportAsComboBox.getSelectedItem();
        FileType fileType = exportFormat.getFileType();
        FileNameExtensionFilter xmlFilter = new FileNameExtensionFilter(
            fileType.getDescription(), fileType.getExtension()
        );
        //this.exportFileChooser.addChoosableFileFilter(xmlFilter);
        this.exportFileChooser.setFileFilter(xmlFilter);
        
        // show the file save chooser dialog
        int userOption = this.exportFileChooser.showSaveDialog(this);
        
        // process the results
        if (userOption == JFileChooser.APPROVE_OPTION) {
            
            // set the default file name extension to the selected format
            String filePath = FileUtil.adjustExtensionFileName(
                this.exportFileChooser.getSelectedFile().getAbsolutePath(), fileType.getExtension()
            );
            
            // update text field visual component
            this.outputFileTextField.setText(filePath);
        }   
    }
    
}
