/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.objectware.editors.msx.sprite.dialogs;

import br.com.objectware.commons.i18n.I18N;
import br.com.objectware.commons.utils.ColorUtil;
import br.com.objectware.commons.utils.Default;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JButton;

/**
 * Select the color code chooser. The dialog colors are disposed accordingly to the palette size.
 * 
 * @author Luciano M. Christofoletti <luciano@objectware.net>
 * @since 31/oct/2015
 */
public class ColorCodeSelectionDialog extends javax.swing.JDialog implements ActionListener {
    
    private enum ACTION {SELECT_COLOR, ACCEPT, CANCEL};
    
    /** The color buttons selection */
    private final java.util.List<JButton> colorCodeButtons = new java.util.ArrayList<>();
    
    /** The selected color code */
    private byte selectedColorCode;
    
    /** Flag used to indicate that a selection was made*/
    private boolean selectionAccepted = false;
    
    /**
     * Creates new form ColorCodeSelectionDialog
     */
    public ColorCodeSelectionDialog(java.awt.Frame parent, boolean modal) {
        
        super(parent, modal);
        
        this.initComponents();
        this.setupListeners();
    }   
    
    /**
     * Set the listeners for visual elements.
     */
    private void setupListeners() {
        this.okButton.addActionListener(this);
        this.cancelButton.addActionListener(this);
    }
    
    /**
     * Set the current palette. The panel is filled with buttons representing the color codes.
     * NOTE: the user selection is cleared when this method is called.
     * @param palette the color palette
     */
    public void setPalette(java.util.List<java.awt.Color> palette) {
        
        // evaluate the color selection table size
        int height = 32 * (palette.size() / 8);
        int width = 48 * (palette.size() / 2);
        
        // adjust the layout to accomodate the color buttons
        this.paletteColorsPanel.setPreferredSize(new java.awt.Dimension(width, height));
        this.paletteColorsPanel.removeAll();
        
        // add the color buttons to the color selection panel
        for(byte k = 0; k < palette.size(); k++) {
            JButton colorButton = this.newColorButton(k, palette.get(k));
            this.paletteColorsPanel.add(colorButton);
        }   
        
        // reset the color selection status
        this.clearUserSelection();
        this.pack();
    }   
    
    /**
     * Set the current selected color code.
     * @param colorCode 
     */
    public void setSelectedColorCode(byte colorCode) {
        this.selectedColorCode = colorCode;
        this.updateSelectedColorCodeButton(colorCode);
    }   
    
    /**
     * Return the selected color code.
     * @return 
     */
    public byte getSelectedColorCode() {
        return this.selectedColorCode;
    }   
    
    /**
     * Status of user selection.
     * @return true if the user accepted the selected color
     */
    public boolean isSelectionAccepted() {
        return this.selectionAccepted;
    }
    
    /**
     * Set/Reset the color code selection status.
     */
    public void clearUserSelection() {
        this.selectionAccepted = false;
        this.selectedColorCode = (byte) -1;
        this.updateSelectedColorCodeButton(this.selectedColorCode);
    }   
    
    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The
     * content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        paletteColorsPanel = new javax.swing.JPanel();
        buttonsPanel = new javax.swing.JPanel();
        okButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle(I18N.getString("select.new.color"));

        paletteColorsPanel.setPreferredSize(new java.awt.Dimension(256, 64));
        paletteColorsPanel.setLayout(new java.awt.GridLayout(2, 8, 2, 2));
        getContentPane().add(paletteColorsPanel, java.awt.BorderLayout.CENTER);

        buttonsPanel.setMinimumSize(new java.awt.Dimension(184, 32));
        buttonsPanel.setPreferredSize(new java.awt.Dimension(412, 38));
        buttonsPanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT, 8, 8));

        org.openide.awt.Mnemonics.setLocalizedText(okButton, I18N.getString("ok"));
        okButton.setActionCommand(ACTION.ACCEPT.name());
        okButton.setMinimumSize(new java.awt.Dimension(80, 23));
        okButton.setPreferredSize(new java.awt.Dimension(80, 23));
        buttonsPanel.add(okButton);

        org.openide.awt.Mnemonics.setLocalizedText(cancelButton, I18N.getString("cancel"));
        cancelButton.setActionCommand(ACTION.CANCEL.name());
        cancelButton.setMinimumSize(new java.awt.Dimension(80, 23));
        cancelButton.setPreferredSize(new java.awt.Dimension(80, 23));
        buttonsPanel.add(cancelButton);

        getContentPane().add(buttonsPanel, java.awt.BorderLayout.PAGE_END);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel buttonsPanel;
    private javax.swing.JButton cancelButton;
    private javax.swing.JButton okButton;
    private javax.swing.JPanel paletteColorsPanel;
    // End of variables declaration//GEN-END:variables

    @Override
    public void actionPerformed(ActionEvent event) {
        
        // the event properties
        Object source = event.getSource();
        ACTION actionCommand = ACTION.valueOf(event.getActionCommand());
        
        switch(actionCommand) {
            
            case SELECT_COLOR:
                byte colorCode = (byte) this.colorCodeButtons.indexOf(source);
                this.setSelectedColorCode(colorCode);
                break;
                
            case ACCEPT:
                this.selectionAccepted = true;
                this.setVisible(false);
                break;
                
            case CANCEL:
                this.setVisible(false);
                break;
        }
    }
    
    /**
     * Create a new color code selector button.
     * @param colorCode the associated color code
     * @param color the color of the button
     * 
     * @return the new button created
     */
    private JButton newColorButton(byte colorCode, java.awt.Color color) {
        
        // the color code visual representation
        JButton colorButton = new JButton(String.format("%02d", colorCode));
        colorButton.setBackground(color);
        colorButton.setForeground(ColorUtil.getContrastColor(color));
        colorButton.setContentAreaFilled(false);
        colorButton.setOpaque(true);
        
        // setup the listener propertie for the button
        colorButton.setActionCommand(ACTION.SELECT_COLOR.name());
        colorButton.addActionListener(this);
        
        // stores the button reference and the color code
        this.colorCodeButtons.add(colorButton);
        
        return colorButton;
    }
    
    /**
     * Update the color code button's text and icon.
     * If the given color code is not contained in the color code buttons map, then
     * no color will appear selected.
     * 
     * @param colorCode the new selected color code
     */
    private void updateSelectedColorCodeButton(byte colorCode) {
        
        // set the selected button for the given color code
        for(byte k = 0; k < this.colorCodeButtons.size(); k++) {
            JButton colorButton = this.colorCodeButtons.get(k);
            if(k == colorCode) {
                colorButton.setText(Default.EMPTY_STRING);
                colorButton.setIcon(I18N.getImageIcon("selection.icon"));
            } else {
                colorButton.setText(String.format("%02d", k));
                colorButton.setIcon(null);
            }
        }
    }
    
}
